defaults:
  - _self_
  - tokenizer: remi_default
  # - model: "music_transfomer_default"

data:
  datapath: data
  save_path: preprocessed_data
name: "music_transformer"
model_dir: model
log_dir: log
predict_dir: predict
vocab_size: 4096
